# ============================================================
# RemoteBioUnlock - server.py
# This is the brain of the app. It listens for unlock requests
# from your phone, validates them, and unlocks your Windows PC.
# ============================================================

import json
import time
import hmac
import hashlib
import subprocess
import ctypes
import os   
import socket 
from flask import Flask, request, jsonify

# ============================================================
# Load configuration from config.json
# ============================================================

BASE_DIR = os.path.dirname(os.path.abspath(__file__)) #searches for the config file where ever it is located, not just in the current working directory. "__file__" is a python var that allows this search.
CONFIG_PATH = os.path.join(BASE_DIR, 'config.json')

with open(CONFIG_PATH, 'r') as f: #loads the Json file and stores it in the "config" variable as a dictionary. The "with" statement ensures that the file is properly closed after reading, even if an error occurs. The R is for read only mode, which is the default mode for open() but is explicitly stated here for clarity and safety.
    config = json.load(f) #Python dictionary that contains the configuration settings for the RemoteBioUnlock application. It is loaded from a JSON file named "config.json" which contains secret key etc.

# Extract configuration values / setters from Json file
SECRET_KEY = config['secret_key'].encode('utf-8')
UNLOCK_PIN = config['unlock_pin']
PORT = config['port']
TOKEN_EXPIRY = config['token_expiry_seconds']

print("[RemoteBioUnlock] Configuration loaded successfully.")

# ============================================================
# Token validation - this is our security checkpoint
# Every incoming request must pass this check or gets rejected
# ============================================================

def validate_token(token: str, timestamp: str) -> bool:
    # Reject requests older than TOKEN_EXPIRY seconds
    try:
        request_time = float(timestamp)
        current_time = time.time()
        if abs(current_time - request_time) > TOKEN_EXPIRY: #checks if the request is older than the allowed expiry time. If it is, it prints a message and returns False, indicating that the token is not valid.
            print("[RemoteBioUnlock] Rejected - request expired.")
            return False
    except ValueError:
        print("[RemoteBioUnlock] Rejected - invalid timestamp.")
        return False

    # Rebuild the expected token and compare
    message = timestamp.encode('utf-8') # uses SHA256 algorithm to create a hash of the timestamp using the secret key. This is done to verify that the token was generated by someone who has the secret key and that it has not been tampered with. The resulting hash is then compared to the token provided in the request to determine if it is valid.
    expected_token = hmac.new(SECRET_KEY, message, hashlib.sha256).hexdigest()

    is_valid = hmac.compare_digest(expected_token, token) #compare_digest is used to protect against timing attacks, which can be used to guess the expected token by measuring the time it takes for the server to respond. If the tokens match, it returns True; otherwise, it returns False. If the token is invalid, it prints a message indicating that the token signature is invalid before returning False.
    if not is_valid:
        print("[RemoteBioUnlock] Rejected - invalid token signature.")
    return is_valid

# ============================================================
# Flask app - this creates our server and defines its endpoints
# ============================================================

app = Flask(__name__)

@app.route('/unlock', methods=['POST']) #only accepts POST requests to the /unlock endpoint. When a request is received at this endpoint, the unlock() function is called to handle the request.
def unlock():
    print("[RemoteBioUnlock] Incoming unlock request...")

#HTTP Status Code Meanings
# 200   ✅ Success 
# 400   ❌ Bad request — you sent something wrong   
# 401   🔒 Unauthorised — token failed  
# 500   💥 Server error — something broke on our end

    # Pull the token and timestamp out of the incoming request
    data = request.get_json()
    if not data:
        print("[RemoteBioUnlock] Rejected - no data received.")
        return jsonify({"status": "error", "message": "No data received."}), 400

    token = data.get('token')
    timestamp = data.get('timestamp')

    if not token or not timestamp:
        print("[RemoteBioUnlock] Rejected - missing token or timestamp.")
        return jsonify({"status": "error", "message": "Missing fields."}), 400

    # Run it through our security checkpoint
    if not validate_token(token, timestamp):
        return jsonify({"status": "error", "message": "Invalid token."}), 401

    # If we get here, the request is legitimate - calls function to unlock the PC
    print("[RemoteBioUnlock] Token valid - attempting unlock...")
    success = unlock_windows()

    if success:
        print("[RemoteBioUnlock] PC unlocked successfully.")
        return jsonify({"status": "success", "message": "PC unlocked."}), 200
    else:
        print("[RemoteBioUnlock] Unlock failed.")
        return jsonify({"status": "error", "message": "Unlock failed."}), 500
    

# ============================================================
# Windows unlock function - this is where the actual unlocking happens
# Win32 API is used here, ctypes is for python to reach windows and wind11.user32 is for peripheral inputs.
# ============================================================


def unlock_windows():
    try:
        # Step 1 - Simulate pressing Ctrl to wake the lock screen
        ctypes.windll.user32.keybd_event(0x11, 0, 0, 0)  # Ctrl down
        ctypes.windll.user32.keybd_event(0x11, 0, 2, 0)  # Ctrl up
        time.sleep(0.5) #change if the pc takes longer to wake up, but 0.5 seconds is usually enough for the lock screen to be ready for input after being woken up. If the lock screen takes longer than this to become active, you may need to increase this delay to ensure that the subsequent key presses are registered correctly.

        # Step 2 - Type the unlock PIN one character at a time
        for character in UNLOCK_PIN:
            vk_code = ord(character.upper())
            ctypes.windll.user32.keybd_event(vk_code, 0, 0, 0)  # Key down
            ctypes.windll.user32.keybd_event(vk_code, 0, 2, 0)  # Key up
            time.sleep(0.05)

        # Step 3 - Preess enter to submit the PIN
        time.sleep(0.1)
        ctypes.windll.user32.keybd_event(0x0D, 0, 0, 0)  # Enter down
        ctypes.windll.user32.keybd_event(0x0D, 0, 2, 0)  # Enter up

        return True

    except Exception as e:
        print(f"[RemoteBioUnlock] Unlock error: {e}")
        return False
    
# ============================================================
# Status endpoint - phone uses this to check if PC is online
# ============================================================

@app.route('/status', methods=['GET'])
def status():
    return jsonify({
        "status": "online",
        "pc_name": config['pc_name'],
        "local_ip": socket.gethostbyname(socket.gethostname())
    }), 200



# ============================================================
# Startup - this runs the server when you launch the script
# ============================================================

if __name__ == '__main__':
    print("=" * 50)
    print("  RemoteBioUnlock Server")
    print(f"  PC Name  : {config['pc_name']}")
    print(f"  Local IP : {socket.gethostbyname(socket.gethostname())}")
    print(f"  Port     : {PORT}")
    print(f"  Status   : Listening for unlock requests...")
    print("=" * 50)

    app.run(
        host='0.0.0.0', # allows the server to accept requests from any IP address on another network, not just from the machine it's running on. This is essential for the phone to communicate with the server.
        port=PORT,
        debug=False,
        ssl_context=None # kept off for simplicity, but you can set up SSL if you want to encrypt the communication between your phone and PC. This would require generating SSL certificates and configuring the server to use them, which is a more advanced setup. future update maybe :
    )



# Small python script to test the server by simulating a phone request. You can run this in your terminal to see how the server responds to an unlock request with a valid token. Just make sure to replace the SECRET_KEY and URL if needed.
#============================================================
#    python -c "
# import hmac, hashlib, time, requests

# SECRET_KEY = 'change-this-to-something-random'
# timestamp = str(time.time())
# message = timestamp.encode('utf-8')
# token = hmac.new(SECRET_KEY.encode('utf-8'), message, hashlib.sha256).hexdigest()

# response = requests.post('http://localhost:5000/unlock', json={'token': token, 'timestamp': timestamp})
# print(response.json())
# "